### ISSUE TITLE
SqlParseException: net.sf.jsqlparser.JSQLParserException

### ISSUE THREAD

**Issue by carstendraschner** [SANSA-Stack/SANSA-Stack#149] opened 2021-03-06 15:40 UTC
When I want to Run a SPARQL Query within SPARQL Frame I face the following Exception.
```
Exception in thread "main" java.lang.RuntimeException: org.aksw.r2rml.jena.sql.transform.SqlParseException: net.sf.jsqlparser.JSQLParserException
	at org.aksw.sparqlify.config.v0_2.bridge.SchemaProviderImpl.createSchemaForRelationName(SchemaProviderImpl.java:63)
	at org.aksw.sparqlify.config.v0_2.bridge.SyntaxBridge.create(SyntaxBridge.java:230)
	at org.aksw.sparqlify.config.v0_2.bridge.ConfiguratorCandidateSelector.configure(ConfiguratorCandidateSelector.java:24)
	at org.aksw.sparqlify.util.SparqlifyUtils.createDefaultSparqlSqlStringRewriter(SparqlifyUtils.java:501)
	at net.sansa_stack.query.spark.sparqlify.SparqlifyUtils3$.createSparqlSqlRewriter(SparqlifyUtils3.scala:64)
	at net.sansa_stack.query.spark.sparqlify.QueryEngineFactorySparqlify.create(QueryEngineFactorySparqlify.scala:13)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparql(package.scala:81)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparqlify(package.scala:85)
	at net.sansa_stack.ml.spark.featureExtraction.SparqlFrame.transform(SparqlFrame.scala:78)
	at net.sansa_stack.ml.spark.featureExtraction.FeatureExtractingSparqlGenerator$.createSparql(FeatureExtractingSparqlGenerator.scala:264)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline$.main(LMDB_Pipeline.scala:73)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline.main(LMDB_Pipeline.scala)
Caused by: org.aksw.r2rml.jena.sql.transform.SqlParseException: net.sf.jsqlparser.JSQLParserException
	at org.aksw.r2rml.sql.transform.SqlUtils.wrapJsqlException(SqlUtils.java:31)
	at org.aksw.r2rml.sql.transform.SqlUtils.harmonizeTableName(SqlUtils.java:46)
	at org.aksw.sparqlify.config.v0_2.bridge.SchemaProviderImpl.createSchemaForRelationName(SchemaProviderImpl.java:61)
	... 11 more
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at org.aksw.r2rml.sql.transform.JSqlUtils.parseTableName(JSqlUtils.java:25)
	at org.aksw.r2rml.sql.transform.SqlUtils.lambda$harmonizeTableName$1(SqlUtils.java:46)
	at org.aksw.r2rml.sql.transform.SqlUtils$$Lambda$3058/0x00000000c6c74820.call(Unknown Source)
	at org.aksw.r2rml.sql.transform.SqlUtils.wrapJsqlException(SqlUtils.java:29)
	... 13 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "-" "-"
    at line 1, column 18.

Was expecting one of:

    ","
    ";"
    "ACTION"
    "ANY"
    "APPLY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "CROSS"
    "CYCLE"
    "DESCRIBE"
    "DISABLE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FULL"
    "GROUP"
    "HAVING"
    "INDEX"
    "INNER"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "ISNULL"
    "JOIN"
    "KEY"
    "LAST"
    "LEFT"
    "MATERIALIZED"
    "MINUS"
    "NATURAL"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NULLS"
    "OPEN"
    "ORDER"
    "OUTER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PIVOT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "STRAIGHT_JOIN"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	... 18 more
```
To reproduce it, you can use the LMDB Pipeline in SANSA ML Examples
In addition, a long output seems to result from a print statement which has been used for debugging
```
[ <http://www.w3.org/ns/r2rml#logicalTable>
          [ <http://www.w3.org/ns/r2rml#tableName>
                    "rdd-1425971970_httpp3ap2fp2fdataclinkedmdbcorgp2fmoviep2fcostume_designer" ] ;
  <http://www.w3.org/ns/r2rml#predicateObjectMap>
          [ <http://www.w3.org/ns/r2rml#objectMap>
                    [ <http://www.w3.org/ns/r2rml#column>
                              "o" ;
                      <http://www.w3.org/ns/r2rml#termType>
                              <http://www.w3.org/ns/r2rml#IRI>
                    ] ;
            <http://www.w3.org/ns/r2rml#predicate>
```
This here is the corresponding SPARQL query
```
val manualSparqlString =
      """
        |SELECT
        |?movie
        |?movie__down_genre__down_film_genre_name
        |?movie__down_date ?movie__down_title
        |?movie__down_runtime ?movie__down_actor__down_actor_name
        |WHERE {
        | ?movie <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/movie/film> .
        | OPTIONAL { ?movie <http://purl.org/dc/terms/date> ?movie__down_date . }
        | OPTIONAL { ?movie <http://purl.org/dc/terms/title> ?movie__down_title . }
        | OPTIONAL { ?movie <http://data.linkedmdb.org/movie/runtime> ?movie__down_runtime . }
        | OPTIONAL { ?movie <http://data.linkedmdb.org/movie/actor> ?movie__down_actor . ?movie__down_actor  <http://data.linkedmdb.org/movie/actor_name> ?movie__down_actor__down_actor_name . }
        | OPTIONAL { ?movie <http://data.linkedmdb.org/movie/genre> ?movie__down_genre . ?movie__down_genre <http://data.linkedmdb.org/movie/film_genre_name> ?movie__down_genre__down_film_genre_name . }
        | }""".stripMargin
```
special information, this exception behavior is not deterministic. in roughly 50% same code run through or result in the reported exception

**Comment by Aklakan** [comment] 2021-03-06 18:53
The issue is due to incorrect quoting of the generated SQL; indicated by Encountered unexpected token: "-" "-"
Setting log output to debug in sansa-test-resources/src/main/resources/log4.properties should reveal the incorrect query strings.

The commit above (together with changes to sparqlify) should fix the issue.

**Comment by carstendraschner** [comment] 2021-03-07 10:53
```
time needed: 17.195039973

CREATE FEATURE EXTRACTING SPARQL
[ <http://www.w3.org/ns/r2rml#logicalTable>
          [ <http://www.w3.org/ns/r2rml#tableName>
                    "\"rdd661885294_httpp3ap2fp2fdataclinkedmdbcorgp2fmoviep2fdirector_name_xmlschemap23string_lang\"" ] ;
  <http://www.w3.org/ns/r2rml#predicateObjectMap>
          [ <http://www.w3.org/ns/r2rml#objectMap>
                    [ <http://www.w3.org/ns/r2rml#column>
                              "\"o\"" ;
                      <http://www.w3.org/ns/r2rml#languageColumn>
                              "\"l\""
                    ] ;
            <http://www.w3.org/ns/r2rml#predicate>
                    <http://data.linkedmdb.org/movie/director_name> ;
            <http://www.w3.org/ns/r2rml#predicateMap>
                    [ <http://www.w3.org/ns/r2rml#constant>
                              <http://data.linkedmdb.org/movie/director_name> ]
          ] ;
  <http://www.w3.org/ns/r2rml#subjectMap>
          [ <http://www.w3.org/ns/r2rml#column>
                    "\"s\"" ;
            <http://www.w3.org/ns/r2rml#termType>
                    <http://www.w3.org/ns/r2rml#IRI>
          ]
] .
# ...

Exception in thread "main" java.lang.RuntimeException: Error processing sqlOp SqlOpTable [tableName="rdd661885294_httpp3ap2fp2fdataclinkedmdbcorgp2fmoviep2fperformance_name_xmlschemap23string_lang", aliasName=null], reason: Column "o" does not exist.
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createMinimalSchema(EffectiveViewGenerator.java:165)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createQuadMaps(EffectiveViewGenerator.java:141)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.transform(EffectiveViewGenerator.java:185)
	at org.aksw.sparqlify.config.v0_2.bridge.ConfiguratorCandidateSelector.configure(ConfiguratorCandidateSelector.java:33)
	at org.aksw.sparqlify.util.SparqlifyUtils.createDefaultSparqlSqlStringRewriter(SparqlifyUtils.java:501)
	at net.sansa_stack.query.spark.sparqlify.SparqlifyUtils3$.createSparqlSqlRewriter(SparqlifyUtils3.scala:64)
	at net.sansa_stack.query.spark.sparqlify.QueryEngineFactorySparqlify.create(QueryEngineFactorySparqlify.scala:13)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparql(package.scala:81)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparqlify(package.scala:85)
	at net.sansa_stack.ml.spark.featureExtraction.SparqlFrame.transform(SparqlFrame.scala:78)
	at net.sansa_stack.ml.spark.featureExtraction.FeatureExtractingSparqlGenerator$.createSparql(FeatureExtractingSparqlGenerator.scala:264)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline$.main(LMDB_Pipeline.scala:73)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline.main(LMDB_Pipeline.scala)
Caused by: java.lang.RuntimeException: Column "o" does not exist.
	at org.aksw.sparqlify.core.sql.schema.SchemaImpl.createSubSchema(SchemaImpl.java:180)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createMinimalSchema(EffectiveViewGenerator.java:163)
	... 12 more

Process finished with exit code 1
```

**Comment by carstendraschner** [comment] 2021-03-07 13:07
with the most recent change of SPARQLIFY, it seems that exception went away

**Comment by Aklakan** [comment] 2021-03-07 15:18
Closing as issue seems to be solved.

**Closed as completed by Aklakan** 2021-03-07 15:18 UTC
