### ISSUE TITLE
Problem on running on CLI

### ISSUE THREAD

**Issue by wiqijan2002** [SANSA-Stack/SANSA-Stack#104] opened 2020-06-27 17:43 UTC
When i run the examples of SANSA-Stack nothing happen as shown in the snapshot[](url)
![sansa](https://user-images.githubusercontent.com/38495673/85928601-966dc380-b8c7-11ea-9652-8dfdf9dcc551.png)

**Comment by Aklakan** [comment] 2020-12-04 09:22
Closing as we cannot reproduce the issue with the current development branch. If there is more information feel free to reopen.

**Closed by Aklakan** 2020-12-04 09:22 UTC
Labels: Examples, Query, Query Spark
